# extract-marquez-lineage.ps1
# Regenerates the Marquez lineage graph as a Mermaid diagram from ground truth.
#
# Queries the Marquez PostgreSQL metadata DB (marquez-db container) and emits
# docs/diagrams/marquez-lineage.mmd. This is the authoritative way to see what the
# lineage store ACTUALLY contains (the Marquez 0.50 /api/v1/lineage REST graph is
# unreliable for these nodeIds; the DB is ground truth).
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts/extract-marquez-lineage.ps1 [-OutPath docs/diagrams/marquez-lineage.mmd]
#
# Requires: docker engine running with the POC stack up (marquez-db container).

param(
    [string]$OutPath = (Join-Path $PSScriptRoot "..\docs\diagrams\marquez-lineage.mmd")
)

$ErrorActionPreference = "Stop"

function Invoke-Msql([string]$Sql) {
    $rows = docker exec marquez-db psql -U marquez -d marquez -t -A -F "`t" -c $Sql 2>$null
    if ($LASTEXITCODE -ne 0) { throw "psql query failed: $Sql" }
    return $rows
}

# --- 1. Datasets / jobs / current edges ------------------------------------
$datasets = Invoke-Msql "SELECT namespace_name, name FROM datasets ORDER BY namespace_name, name;"
$jobs     = Invoke-Msql "SELECT namespace_name, name FROM jobs ORDER BY namespace_name, name;"
$edges    = Invoke-Msql @"
SELECT j.namespace_name||':'||j.name, d.namespace_name||':'||d.name, m.io_type
FROM job_versions_io_mapping m
JOIN job_versions jv ON m.job_version_uuid = jv.uuid
JOIN jobs j           ON jv.job_uuid       = j.uuid
JOIN datasets d       ON m.dataset_uuid    = d.uuid
WHERE m.is_current_job_version
ORDER BY m.io_type, 1;
"@

# --- 2. Sanitize identifiers for mermaid -----------------------------------
function Get-MermaidId([string]$S) {
    return ($S -replace '[^A-Za-z0-9_]', '_')
}
function Get-Label([string]$S) {
    return $S.Replace('|', '\|').Replace('[', '\[').Replace(']', '\]')
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("flowchart LR")
[void]$sb.AppendLine("    %% Generated by scripts/extract-marquez-lineage.ps1 from the Marquez metadata DB.")
[void]$sb.AppendLine("    %% Solid edges = dataset INPUT/OUTPUT edges recorded in job_versions_io_mapping (current job versions).")

# Datasets grouped by namespace
$dsByNs = $datasets | ForEach-Object {
    $p = $_ -split "`t", 2; [PSCustomObject]@{ Ns = $p[0]; Name = $p[1] }
} | Group-Object Ns
$nsIdx = 0
foreach ($g in $dsByNs) {
    $gid = "DS_$($nsIdx++)"
    [void]$sb.AppendLine("    subgraph $gid[""$($g.Name -replace '"','' )""]")
    foreach ($d in $g.Group) {
        $id = "D_" + (Get-MermaidId "$($d.Ns)/$($d.Name)")
        [void]$sb.AppendLine("        $id[""$(Get-Label $d.Name)""]")
    }
    [void]$sb.AppendLine("    end")
}

# Jobs grouped by namespace
$jbByNs = $jobs | ForEach-Object {
    $p = $_ -split "`t", 2; [PSCustomObject]@{ Ns = $p[0]; Name = $p[1] }
} | Group-Object Ns
$nsIdx = 0
foreach ($g in $jbByNs) {
    $gid = "JB_$($nsIdx++)"
    [void]$sb.AppendLine("    subgraph $gid[""jobs: $($g.Name -replace '"','' )""]")
    foreach ($j in $g.Group) {
        $id = "J_" + (Get-MermaidId "$($j.Ns)/$($j.Name)")
        [void]$sb.AppendLine("        $id[$(Get-Label $j.Name)]")
    }
    [void]$sb.AppendLine("    end")
}

# Edges: INPUT  dataset --> job ; OUTPUT job --> dataset
foreach ($e in $edges) {
    $p = $e -split "`t", 3
    $job = $p[0]; $ds = $p[1]; $io = $p[2]
    $jid = "J_" + (Get-MermaidId $job)
    $did = "D_" + (Get-MermaidId $ds)
    if ($io -eq "INPUT") {
        [void]$sb.AppendLine("    $did -->|INPUT| $jid")
    } else {
        [void]$sb.AppendLine("    $jid -->|OUTPUT| $did")
    }
}

# --- 3. Write ----------------------------------------------------------------
$abs = [System.IO.Path]::GetFullPath($OutPath)
$dir = [System.IO.Path]::GetDirectoryName($abs)
[System.IO.Directory]::CreateDirectory($dir) | Out-Null
Set-Content -Encoding utf8 -Path $abs -Value $sb.ToString()
Write-Output "Wrote $abs"
Write-Output ("  datasets: " + $datasets.Count + "  jobs: " + $jobs.Count + "  current edges: " + $edges.Count)